services:
  rikkahub:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/longyq20/rikkahub:webdist
    container_name: rikkahub
    ports:
      - "8080:8080"
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DATA_DIR: /data
      WEB_UI_DIR: /app/web-ui
      ASSETS_DIR: /app/assets
      JWT_ENABLED: "false"
    volumes:
      - ./data:/data
    restart: unless-stopped
